{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                 High        Low       Open      Close     Volume  Adj Close\n",
      "Date                                                                        \n",
      "2010-01-04  20.430000  19.900000  19.920000  20.240000  2171500.0  17.347511\n",
      "2010-01-05  20.320000  19.930000  19.930000  20.299999  1481700.0  17.398933\n",
      "2010-01-06  20.360001  20.160000  20.200001  20.290001  2446700.0  17.390356\n",
      "2010-01-07  20.299999  19.889999  20.250000  20.020000  2832800.0  17.158953\n",
      "2010-01-08  20.299999  19.879999  20.030001  20.230000  1449200.0  17.338934\n",
      "...               ...        ...        ...        ...        ...        ...\n",
      "2017-12-22  76.129997  75.349998  75.610001  76.089996   796500.0  71.781937\n",
      "2017-12-26  76.250000  75.839996  76.250000  76.129997   520700.0  71.819672\n",
      "2017-12-27  76.830002  76.029999  76.180000  76.339996   662800.0  72.017769\n",
      "2017-12-28  76.739998  76.300003  76.349998  76.669998   469800.0  72.329094\n",
      "2017-12-29  77.169998  76.599998  76.800003  76.830002   923300.0  72.480049\n",
      "\n",
      "[2013 rows x 6 columns]\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [08/Apr/2021 15:54:10] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [08/Apr/2021 15:54:10] \"\u001b[37mGET /_dash-dependencies HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [08/Apr/2021 15:54:10] \"\u001b[37mGET /favicon.ico HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [08/Apr/2021 15:54:10] \"\u001b[37mGET /_dash-layout HTTP/1.1\u001b[0m\" 200 -\n",
      "[2021-04-08 15:54:10,840] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 558, in dispatch\n",
      "    return self.callback_map[target_id]['callback'](*args)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 515, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-1-42b1e38968e1>\", line 87, in update_figure\n",
      "    st2 = st[(st.Date > dates[input2[0]]) & (st.Date < dates[input2[1]])]\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py\", line 5139, in __getattr__\n",
      "    return object.__getattribute__(self, name)\n",
      "AttributeError: 'DataFrame' object has no attribute 'Date'\n",
      "127.0.0.1 - - [08/Apr/2021 15:54:10] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2021-04-08 15:54:14,177] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 558, in dispatch\n",
      "    return self.callback_map[target_id]['callback'](*args)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 515, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-1-42b1e38968e1>\", line 87, in update_figure\n",
      "    st2 = st[(st.Date > dates[input2[0]]) & (st.Date < dates[input2[1]])]\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py\", line 5139, in __getattr__\n",
      "    return object.__getattribute__(self, name)\n",
      "AttributeError: 'DataFrame' object has no attribute 'Date'\n",
      "127.0.0.1 - - [08/Apr/2021 15:54:14] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2021-04-08 15:57:36,532] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 558, in dispatch\n",
      "    return self.callback_map[target_id]['callback'](*args)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 515, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-1-42b1e38968e1>\", line 87, in update_figure\n",
      "    st2 = st[(st.Date > dates[input2[0]]) & (st.Date < dates[input2[1]])]\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py\", line 5139, in __getattr__\n",
      "    return object.__getattribute__(self, name)\n",
      "AttributeError: 'DataFrame' object has no attribute 'Date'\n",
      "127.0.0.1 - - [08/Apr/2021 15:57:36] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2021-04-08 15:57:37,998] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 558, in dispatch\n",
      "    return self.callback_map[target_id]['callback'](*args)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 515, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-1-42b1e38968e1>\", line 87, in update_figure\n",
      "    st2 = st[(st.Date > dates[input2[0]]) & (st.Date < dates[input2[1]])]\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py\", line 5139, in __getattr__\n",
      "    return object.__getattribute__(self, name)\n",
      "AttributeError: 'DataFrame' object has no attribute 'Date'\n",
      "127.0.0.1 - - [08/Apr/2021 15:57:38] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2021-04-08 15:57:39,133] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 558, in dispatch\n",
      "    return self.callback_map[target_id]['callback'](*args)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 515, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-1-42b1e38968e1>\", line 87, in update_figure\n",
      "    st2 = st[(st.Date > dates[input2[0]]) & (st.Date < dates[input2[1]])]\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py\", line 5139, in __getattr__\n",
      "    return object.__getattribute__(self, name)\n",
      "AttributeError: 'DataFrame' object has no attribute 'Date'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [08/Apr/2021 15:57:39] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2021-04-08 15:57:39,757] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 558, in dispatch\n",
      "    return self.callback_map[target_id]['callback'](*args)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 515, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-1-42b1e38968e1>\", line 87, in update_figure\n",
      "    st2 = st[(st.Date > dates[input2[0]]) & (st.Date < dates[input2[1]])]\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py\", line 5139, in __getattr__\n",
      "    return object.__getattribute__(self, name)\n",
      "AttributeError: 'DataFrame' object has no attribute 'Date'\n",
      "127.0.0.1 - - [08/Apr/2021 15:57:39] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2021-04-08 15:57:41,205] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 558, in dispatch\n",
      "    return self.callback_map[target_id]['callback'](*args)\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 515, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-1-42b1e38968e1>\", line 87, in update_figure\n",
      "    st2 = st[(st.Date > dates[input2[0]]) & (st.Date < dates[input2[1]])]\n",
      "  File \"/Users/cianmoynagh/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py\", line 5139, in __getattr__\n",
      "    return object.__getattribute__(self, name)\n",
      "AttributeError: 'DataFrame' object has no attribute 'Date'\n",
      "127.0.0.1 - - [08/Apr/2021 15:57:41] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "import dash\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "from dash.dependencies import Input, Output\n",
    "\n",
    "from pandas_datareader import DataReader # pip install pandas-datareader\n",
    "from pandas_datareader import data\n",
    "\n",
    "\n",
    "import pandas as pd\n",
    "import plotly.graph_objs as go\n",
    "\n",
    "# Step 1. Launch the application\n",
    "app = dash.Dash()\n",
    "\n",
    "# Step 2. Import the dataset\n",
    "\n",
    "start = pd.to_datetime('2010-01-01') # in YYYY-MM-DD format\n",
    "end = pd.to_datetime('2018-01-01')\n",
    "st = data.DataReader('NDAQ', 'yahoo', start , end) # here 'yahoo' is the API to yah\n",
    "\n",
    "print(st)\n",
    "#filepath = 'https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv'\n",
    "#st = pd.read_csv(filepath)\n",
    "\n",
    "# dropdown options (should be changed to each model)\n",
    "features = st.columns[1:-1]\n",
    "opts = [{'label' : i, 'value' : i} for i in features]\n",
    "\n",
    "# range slider options\n",
    "st['High'] = pd.to_datetime(st.High)\n",
    "dates = ['2015-02-17', '2015-05-17', '2015-08-17', '2015-11-17',\n",
    "         '2016-02-17', '2016-05-17', '2016-08-17', '2016-11-17', '2017-02-17']\n",
    "\n",
    "\n",
    "# Step 3. Create a plotly figure\n",
    "trace_1 = go.Scatter(x = st.Close, y = st['Close'],\n",
    "                    name = 'Close',\n",
    "                    line = dict(width = 2,\n",
    "                                color = 'rgb(229, 151, 50)'))\n",
    "layout = go.Layout(title = 'Time Series Plot',\n",
    "                   hovermode = 'closest')\n",
    "fig = go.Figure(data = [trace_1], layout = layout)\n",
    "\n",
    "\n",
    "# Step 4. Create a Dash layout\n",
    "app.layout = html.Div([\n",
    "                # a header and a paragraph\n",
    "                html.Div([\n",
    "                    html.H1(\"Time Series Analysis on Stocks Prediction\"),\n",
    "                    html.P(\"Group 40\")\n",
    "                         ],\n",
    "                     style = {'padding' : '50px' ,\n",
    "                              'backgroundColor' : '#a12f0a'}),\n",
    "                # adding a plot\n",
    "                dcc.Graph(id = 'plot', figure = fig),\n",
    "                # dropdown\n",
    "                html.P([\n",
    "                    html.Label(\"Choose a Model\"),\n",
    "                    dcc.Dropdown(id = 'opt', options = opts,\n",
    "                                value = opts[0])\n",
    "                        ], style = {'width': '400px',\n",
    "                                    'fontSize' : '20px',\n",
    "                                    'padding-left' : '100px',\n",
    "                                    'display': 'inline-block'}),\n",
    "                # range slider\n",
    "                html.P([\n",
    "                    html.Label(\"Time Period\"),\n",
    "                    dcc.RangeSlider(id = 'slider',\n",
    "                                    marks = {i : dates[i] for i in range(0, 9)},\n",
    "                                    min = 0,\n",
    "                                    max = 8,\n",
    "                                    value = [1, 7])\n",
    "                        ], style = {'width' : '80%',\n",
    "                                    'fontSize' : '20px',\n",
    "                                    'padding-left' : '100px',\n",
    "                                    'display': 'inline-block'})\n",
    "                      ])\n",
    "\n",
    "\n",
    "# Step 5. Add callback functions\n",
    "@app.callback(Output('plot', 'figure'),\n",
    "             [Input('opt', 'value'),\n",
    "             Input('slider', 'value')])\n",
    "def update_figure(input1, input2):\n",
    "    # filtering the data\n",
    "    st2 = st[(st.Date > dates[input2[0]]) & (st.Date < dates[input2[1]])]\n",
    "    # updating the plot\n",
    "    trace_1 = go.Scatter(x = st2.Date, y = st2['High'],\n",
    "                        name = 'High',\n",
    "                        line = dict(width = 2,\n",
    "                                    color = 'rgb(229, 151, 50)'))\n",
    "    trace_2 = go.Scatter(x = st2.Date, y = st2[input1],\n",
    "                        name = input1,\n",
    "                        line = dict(width = 2,\n",
    "                                    color = 'rgb(106, 181, 135)'))\n",
    "    fig = go.Figure(data = [trace_1, trace_2], layout = layout)\n",
    "    return fig\n",
    "  \n",
    "# Step 6. Add the server clause\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "app.run_server()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
